### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by jcordes73** [EnMasseProject/openshift-configuration#21]
Right now the broker is unauthenticated, i.e. you can access it without providing username and password when connecting from a client.

**Comment by lulf** [comment]
The idea here is to integrate with keycloak to support authentication in the messaging service, though we have not yet started this task. FWIW, we're tracking a backlog of few high-level tasks here: https://github.com/orgs/EnMasseProject/projects/1

**Comment by jcordes73** [comment]
@lulf Unfortunately https://github.com/orgs/EnMasseProject/projects/1 gives me a 404. Would love to have a look at this ...

**Comment by lulf** [comment]
This issue was moved to EnMasseProject/enmasse#6
