### ISSUE TITLE
Convert DeploymentConfig+Imagestream to kubernetes Deployment

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/openshift-configuration#33]

**Comment by grs** [comment]
What version(s) of openshift  will run the Deployment? (Just wondering whether we need to add Deployment alongside the current DeploymentConfig+Imagestream or whether we can safely replace?

**Comment by lulf** [comment]
It should work on 1.3 of OpenShift. I will test with 1.3 and 1.4 to make sure.

**Comment by grs** [comment]
Great, thanks Ulf!
